{
  description = "rust-analyzer's workspace built one Cargo unit at a time, by nix-cargo-unit";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # Resolved against whatever tree this flake was fetched from, so
    # `nix build "path:<repo>?dir=bench/rust-analyzer"` and, once bench/ is
    # tracked, `nix build ./bench/rust-analyzer` both land on the repo root.
    nix-cargo-unit = {
      url = "path:../..";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    nixpkgs,
    nix-cargo-unit,
    ...
  }: let
    systems = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
    forAllSystems = fn: nixpkgs.lib.genAttrs systems (system: fn nixpkgs.legacyPackages.${system});

    # The whole pipeline, from Cargo.lock to a built workspace. Every stage is a
    # derivation; nothing here is generated by hand or checked in.
    #
    #   Cargo.lock ──> vendor ──┬─> cargo build --unit-graph ──> unitGraph
    #                           └─> nix-cargo-unit render ─────> units.nix
    #                                                              │ (IFD)
    #                                             one derivation per compile unit
    workspaceFor = pkgs: let
      inherit (pkgs) lib;

      # `--profile` for the planning pass. The profile is baked into every unit
      # hash, so changing it re-renders and rebuilds the graph.
      profile = "release";

      # This flake's own directory *is* the Cargo workspace. The same store path
      # is handed to cargo, to the renderer's `--workspace-root`, and to the
      # rendered `workspaceRoot`, so the relative paths the renderer records line
      # up with the tree the units are built from.
      workspaceSrc = ./.;

      # `rustc` in nixpkgs is a thin wrapper that only forwards `$NIX_RUSTFLAGS`
      # and ships `bin/` alone; the unwrapped derivation is the one carrying
      # `lib/rustlib`, which the rendered units reference for the std
      # `--remap-path-prefix` and for `llvm-cov`.
      rustToolchain = pkgs.symlinkJoin {
        name = "cargo-unit-rust-toolchain-${pkgs.rustc.version}";
        paths = [
          pkgs.rustc.unwrapped
          pkgs.cargo
          pkgs.clippy
          pkgs.rustfmt
        ];
      };

      # Salting unit hashes with the compiler identity makes a nixpkgs bump
      # invalidate the graph instead of silently reusing artifacts built by a
      # different rustc.
      toolchainId = "rustc-${pkgs.rustc.version}";

      ## ---------------------------------------------------------------- vendor

      lock = builtins.fromTOML (builtins.readFile ./Cargo.lock);

      # Path-only packages (the workspace's own crates) carry no `source`; they
      # are built from `workspaceRoot`, not from here.
      externals = lib.filter (package: package ? source) lock.package;

      unfetchable =
        lib.filter
        (package: !(lib.hasPrefix "registry+" package.source || lib.hasPrefix "sparse+" package.source))
        externals;

      # One derivation per crate, so a unit depends on its own `.crate` tarball
      # rather than on the whole vendor tree.
      crateSource = package:
        pkgs.runCommand "cargo-unit-vendor-${package.name}-${package.version}" {
          src = pkgs.fetchurl {
            name = "${package.name}-${package.version}.crate";
            url = "https://static.crates.io/crates/${package.name}/${package.name}-${package.version}.crate";
            sha256 = package.checksum;
          };
          preferLocalBuild = true;
        } ''
          mkdir -p "$out"
          tar -xzf "$src" --strip-components=1 -C "$out"
          chmod -R u+w "$out"
          # Cargo verifies a directory source against `package` only; `files` is
          # allowed to be empty, which is also what `importCargoLock` emits.
          printf '{"files":{},"package":"%s"}' ${lib.escapeShellArg package.checksum} \
            > "$out/.cargo-checksum.json"
        '';

      vendorEntries =
        map (package: {
          # `<name>-<version>`, so two versions of one crate can coexist.
          name = "${package.name}-${package.version}";
          # How nix-cargo-unit keys an external unit (README §6.2): the source
          # string comes from Cargo.lock, not from the unit graph.
          key = "${package.source}#${package.name}@${package.version}";
          path = crateSource package;
        })
        externals;

      vendorSources = lib.listToAttrs (map (entry: lib.nameValuePair entry.key entry.path) vendorEntries);

      # Real files, not a `linkFarm` and not `cp -rs`: the renderer walks this
      # tree when it scopes a source closure and rejects a symlink that leaves
      # `--vendor-root` ("points outside source boundary"). Cargo plans against
      # this directory and records `src_path` verbatim; the renderer strips the
      # vendor root back off it, so both sides must see the same layout.
      vendorDir = pkgs.runCommand "cargo-unit-vendor" {preferLocalBuild = true;} ''
        mkdir -p "$out"
        ${lib.concatMapStringsSep "\n" (entry: ''
            cp -r ${lib.escapeShellArg entry.path} "$out"/${lib.escapeShellArg entry.name}
          '')
          vendorEntries}
        chmod -R u+w "$out"
      '';

      ## ------------------------------------------------------------ unit graph

      # Planning only: cargo resolves features and enumerates units, compiling
      # nothing. `--unit-graph` is still behind `-Z unstable-options` and nixpkgs
      # ships a stable cargo, hence the bootstrap escape hatch.
      unitGraph =
        pkgs.runCommand "rust-analyzer-unit-graph.json" {
          nativeBuildInputs = [rustToolchain];
        } ''
          export HOME="$NIX_BUILD_TOP/home"
          export CARGO_HOME="$NIX_BUILD_TOP/cargo-home"
          export CARGO_TARGET_DIR="$NIX_BUILD_TOP/target"
          export RUSTC_BOOTSTRAP=1
          mkdir -p "$HOME" "$CARGO_HOME"

          cat > "$CARGO_HOME/config.toml" <<EOF
          [source.crates-io]
          replace-with = "vendored-sources"

          [source.vendored-sources]
          directory = "${vendorDir}"
          EOF

          cd ${workspaceSrc}
          cargo build \
            --offline \
            --locked \
            --workspace \
            --profile ${profile} \
            --unit-graph -Z unstable-options \
            > "$out"
        '';

      ## ---------------------------------------------------------------- render

      unitsNix =
        pkgs.runCommand "rust-analyzer-units.nix" {
          nativeBuildInputs = [nix-cargo-unit.packages.${pkgs.stdenv.hostPlatform.system}.nix-cargo-unit];
        } ''
          nix-cargo-unit render \
            --workspace-root ${workspaceSrc} \
            --vendor-root ${vendorDir} \
            --cargo-lock ${workspaceSrc}/Cargo.lock \
            --toolchain-id ${lib.escapeShellArg toolchainId} \
            < ${unitGraph} \
            > "$out"
        '';

      ## ----------------------------------------------------------------- build

      # Import-from-derivation: `unitsNix` is realised during evaluation, and
      # every Cargo compile unit below is a derivation of its own.
      rendered = import unitsNix {
        inherit pkgs rustToolchain vendorDir vendorSources;
        src = workspaceSrc;
        workspaceRoot = workspaceSrc;

        # Per-unit clippy is a separate gate, not part of building the workspace.
        clippyEnabled = false;
      };

      # `rendered.default` is only the graph's first root. The whole workspace is
      # every root: each member crate's library and binary targets.
      #
      # `pathsToLink` drops each unit's `nix-support/extern-path`, the pointer
      # the renderer uses to wire one unit's rlib into the next. Every root
      # carries one, they all collide, and none of them means anything once the
      # units are merged into a single tree.
      workspace = pkgs.buildEnv {
        name = "rust-analyzer-workspace";
        paths = rendered.roots;
        pathsToLink = [
          "/bin"
          "/lib"
        ];
      };
    in
      assert lib.assertMsg (unfetchable == []) ''
        This flake only knows how to fetch registry crates from Cargo.lock. ${lib.concatMapStringsSep ", " (p: "${p.name} ${p.version} (${p.source})") unfetchable} needs a git or path fetcher.
      '';
        rendered
        // {
          inherit
            rustToolchain
            unitGraph
            unitsNix
            vendorDir
            vendorSources
            workspace
            ;
        };
  in {
    packages = forAllSystems (
      pkgs: let
        ra = workspaceFor pkgs;
      in {
        # Every workspace root in one tree: the point of the exercise.
        default = ra.workspace;
        inherit (ra) workspace;

        rust-analyzer = ra.binaries."rust-analyzer";
        rust-analyzer-proc-macro-srv = ra.binaries."rust-analyzer-proc-macro-srv";

        # The pipeline's intermediate stages, buildable on their own when a
        # render or a planning problem needs to be looked at directly.
        inherit (ra) unitGraph unitsNix vendorDir rustToolchain;

        # Individual compile units and per-target sets, e.g.
        # `nix build '.#units."syntax-0.0.0-<hash>"'`.
        inherit
          (ra)
          units
          packages
          binaries
          libraries
          ;
      }
    );

    checks = forAllSystems (
      pkgs: let
        ra = workspaceFor pkgs;
      in {
        # The unit graph only proves the pieces link. This proves the linked
        # binary is the real one: it answers `--version` and its parser produces
        # a syntax tree, so a mislinked or truncated artifact still fails here.
        smoke =
          pkgs.runCommand "rust-analyzer-smoke" {
            nativeBuildInputs = [ra.binaries."rust-analyzer"];
          } ''
            rust-analyzer --version | tee version.txt
            grep -q '^rust-analyzer ' version.txt

            printf 'fn main() { let x: i32 = 1; }\n' > input.rs
            rust-analyzer parse < input.rs | tee parsed.txt
            grep -q 'SOURCE_FILE@' parsed.txt
            # `!` keeps `set -e` from tripping on grep's no-match exit.
            ! grep -qi 'error' parsed.txt

            mkdir -p "$out"
            cp version.txt parsed.txt "$out"/
          '';
      }
    );

    # The cargo/rustc the units are built with, for poking at the workspace by
    # hand. Not used by the build itself.
    devShells = forAllSystems (pkgs: {
      default = pkgs.mkShell {
        packages = [(workspaceFor pkgs).rustToolchain];
      };
    });

    # Matches the parent repository's formatter.
    formatter = forAllSystems (pkgs: pkgs.alejandra);
  };
}
